use ::libc;
pub type C2RustUnnamed = libc::c_uint;
pub const _sch_isbasic: C2RustUnnamed = 3088;
pub const _sch_iscppsp: C2RustUnnamed = 3072;
pub const _sch_isgraph: C2RustUnnamed = 172;
pub const _sch_isidnum: C2RustUnnamed = 516;
pub const _sch_isalnum: C2RustUnnamed = 140;
pub const _sch_isalpha: C2RustUnnamed = 136;
pub const _sch_isnvsp: C2RustUnnamed = 2048;
pub const _sch_isvsp: C2RustUnnamed = 1024;
pub const _sch_isidst: C2RustUnnamed = 512;
pub const _sch_isxdigit: C2RustUnnamed = 256;
pub const _sch_isupper: C2RustUnnamed = 128;
pub const _sch_isspace: C2RustUnnamed = 64;
pub const _sch_ispunct: C2RustUnnamed = 32;
pub const _sch_isprint: C2RustUnnamed = 16;
pub const _sch_islower: C2RustUnnamed = 8;
pub const _sch_isdigit: C2RustUnnamed = 4;
pub const _sch_iscntrl: C2RustUnnamed = 2;
pub const _sch_isblank: C2RustUnnamed = 1;
#[no_mangle]
pub static mut _sch_istable: [libc::c_ushort; 256] = [
    (_sch_isnvsp as libc::c_int | _sch_iscntrl as libc::c_int) as libc::c_ushort,
    _sch_iscntrl as libc::c_int as libc::c_ushort,
    _sch_iscntrl as libc::c_int as libc::c_ushort,
    _sch_iscntrl as libc::c_int as libc::c_ushort,
    _sch_iscntrl as libc::c_int as libc::c_ushort,
    _sch_iscntrl as libc::c_int as libc::c_ushort,
    _sch_iscntrl as libc::c_int as libc::c_ushort,
    _sch_iscntrl as libc::c_int as libc::c_ushort,
    _sch_iscntrl as libc::c_int as libc::c_ushort,
    (_sch_isnvsp as libc::c_int | _sch_isspace as libc::c_int
        | _sch_isblank as libc::c_int | _sch_iscntrl as libc::c_int) as libc::c_ushort,
    (_sch_isvsp as libc::c_int | _sch_isspace as libc::c_int
        | _sch_iscntrl as libc::c_int) as libc::c_ushort,
    (_sch_isnvsp as libc::c_int | _sch_isspace as libc::c_int
        | _sch_iscntrl as libc::c_int) as libc::c_ushort,
    (_sch_isnvsp as libc::c_int | _sch_isspace as libc::c_int
        | _sch_iscntrl as libc::c_int) as libc::c_ushort,
    (_sch_isvsp as libc::c_int | _sch_isspace as libc::c_int
        | _sch_iscntrl as libc::c_int) as libc::c_ushort,
    _sch_iscntrl as libc::c_int as libc::c_ushort,
    _sch_iscntrl as libc::c_int as libc::c_ushort,
    _sch_iscntrl as libc::c_int as libc::c_ushort,
    _sch_iscntrl as libc::c_int as libc::c_ushort,
    _sch_iscntrl as libc::c_int as libc::c_ushort,
    _sch_iscntrl as libc::c_int as libc::c_ushort,
    _sch_iscntrl as libc::c_int as libc::c_ushort,
    _sch_iscntrl as libc::c_int as libc::c_ushort,
    _sch_iscntrl as libc::c_int as libc::c_ushort,
    _sch_iscntrl as libc::c_int as libc::c_ushort,
    _sch_iscntrl as libc::c_int as libc::c_ushort,
    _sch_iscntrl as libc::c_int as libc::c_ushort,
    _sch_iscntrl as libc::c_int as libc::c_ushort,
    _sch_iscntrl as libc::c_int as libc::c_ushort,
    _sch_iscntrl as libc::c_int as libc::c_ushort,
    _sch_iscntrl as libc::c_int as libc::c_ushort,
    _sch_iscntrl as libc::c_int as libc::c_ushort,
    _sch_iscntrl as libc::c_int as libc::c_ushort,
    (_sch_isnvsp as libc::c_int | _sch_isspace as libc::c_int
        | _sch_isblank as libc::c_int | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_ispunct as libc::c_int | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_ispunct as libc::c_int | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_ispunct as libc::c_int | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_ispunct as libc::c_int | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_ispunct as libc::c_int | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_ispunct as libc::c_int | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_ispunct as libc::c_int | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_ispunct as libc::c_int | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_ispunct as libc::c_int | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_ispunct as libc::c_int | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_ispunct as libc::c_int | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_ispunct as libc::c_int | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_ispunct as libc::c_int | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_ispunct as libc::c_int | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_ispunct as libc::c_int | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_isdigit as libc::c_int | _sch_isxdigit as libc::c_int
        | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_isdigit as libc::c_int | _sch_isxdigit as libc::c_int
        | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_isdigit as libc::c_int | _sch_isxdigit as libc::c_int
        | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_isdigit as libc::c_int | _sch_isxdigit as libc::c_int
        | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_isdigit as libc::c_int | _sch_isxdigit as libc::c_int
        | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_isdigit as libc::c_int | _sch_isxdigit as libc::c_int
        | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_isdigit as libc::c_int | _sch_isxdigit as libc::c_int
        | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_isdigit as libc::c_int | _sch_isxdigit as libc::c_int
        | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_isdigit as libc::c_int | _sch_isxdigit as libc::c_int
        | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_isdigit as libc::c_int | _sch_isxdigit as libc::c_int
        | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_ispunct as libc::c_int | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_ispunct as libc::c_int | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_ispunct as libc::c_int | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_ispunct as libc::c_int | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_ispunct as libc::c_int | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_ispunct as libc::c_int | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_ispunct as libc::c_int | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_isupper as libc::c_int | _sch_isidst as libc::c_int
        | _sch_isxdigit as libc::c_int | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_isupper as libc::c_int | _sch_isidst as libc::c_int
        | _sch_isxdigit as libc::c_int | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_isupper as libc::c_int | _sch_isidst as libc::c_int
        | _sch_isxdigit as libc::c_int | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_isupper as libc::c_int | _sch_isidst as libc::c_int
        | _sch_isxdigit as libc::c_int | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_isupper as libc::c_int | _sch_isidst as libc::c_int
        | _sch_isxdigit as libc::c_int | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_isupper as libc::c_int | _sch_isidst as libc::c_int
        | _sch_isxdigit as libc::c_int | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_isupper as libc::c_int | _sch_isidst as libc::c_int
        | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_isupper as libc::c_int | _sch_isidst as libc::c_int
        | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_isupper as libc::c_int | _sch_isidst as libc::c_int
        | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_isupper as libc::c_int | _sch_isidst as libc::c_int
        | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_isupper as libc::c_int | _sch_isidst as libc::c_int
        | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_isupper as libc::c_int | _sch_isidst as libc::c_int
        | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_isupper as libc::c_int | _sch_isidst as libc::c_int
        | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_isupper as libc::c_int | _sch_isidst as libc::c_int
        | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_isupper as libc::c_int | _sch_isidst as libc::c_int
        | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_isupper as libc::c_int | _sch_isidst as libc::c_int
        | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_isupper as libc::c_int | _sch_isidst as libc::c_int
        | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_isupper as libc::c_int | _sch_isidst as libc::c_int
        | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_isupper as libc::c_int | _sch_isidst as libc::c_int
        | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_isupper as libc::c_int | _sch_isidst as libc::c_int
        | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_isupper as libc::c_int | _sch_isidst as libc::c_int
        | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_isupper as libc::c_int | _sch_isidst as libc::c_int
        | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_isupper as libc::c_int | _sch_isidst as libc::c_int
        | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_isupper as libc::c_int | _sch_isidst as libc::c_int
        | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_isupper as libc::c_int | _sch_isidst as libc::c_int
        | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_isupper as libc::c_int | _sch_isidst as libc::c_int
        | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_ispunct as libc::c_int | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_ispunct as libc::c_int | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_ispunct as libc::c_int | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_ispunct as libc::c_int | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_ispunct as libc::c_int | _sch_isidst as libc::c_int
        | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_ispunct as libc::c_int | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_islower as libc::c_int | _sch_isidst as libc::c_int
        | _sch_isxdigit as libc::c_int | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_islower as libc::c_int | _sch_isidst as libc::c_int
        | _sch_isxdigit as libc::c_int | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_islower as libc::c_int | _sch_isidst as libc::c_int
        | _sch_isxdigit as libc::c_int | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_islower as libc::c_int | _sch_isidst as libc::c_int
        | _sch_isxdigit as libc::c_int | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_islower as libc::c_int | _sch_isidst as libc::c_int
        | _sch_isxdigit as libc::c_int | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_islower as libc::c_int | _sch_isidst as libc::c_int
        | _sch_isxdigit as libc::c_int | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_islower as libc::c_int | _sch_isidst as libc::c_int
        | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_islower as libc::c_int | _sch_isidst as libc::c_int
        | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_islower as libc::c_int | _sch_isidst as libc::c_int
        | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_islower as libc::c_int | _sch_isidst as libc::c_int
        | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_islower as libc::c_int | _sch_isidst as libc::c_int
        | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_islower as libc::c_int | _sch_isidst as libc::c_int
        | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_islower as libc::c_int | _sch_isidst as libc::c_int
        | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_islower as libc::c_int | _sch_isidst as libc::c_int
        | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_islower as libc::c_int | _sch_isidst as libc::c_int
        | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_islower as libc::c_int | _sch_isidst as libc::c_int
        | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_islower as libc::c_int | _sch_isidst as libc::c_int
        | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_islower as libc::c_int | _sch_isidst as libc::c_int
        | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_islower as libc::c_int | _sch_isidst as libc::c_int
        | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_islower as libc::c_int | _sch_isidst as libc::c_int
        | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_islower as libc::c_int | _sch_isidst as libc::c_int
        | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_islower as libc::c_int | _sch_isidst as libc::c_int
        | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_islower as libc::c_int | _sch_isidst as libc::c_int
        | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_islower as libc::c_int | _sch_isidst as libc::c_int
        | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_islower as libc::c_int | _sch_isidst as libc::c_int
        | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_islower as libc::c_int | _sch_isidst as libc::c_int
        | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_ispunct as libc::c_int | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_ispunct as libc::c_int | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_ispunct as libc::c_int | _sch_isprint as libc::c_int) as libc::c_ushort,
    (_sch_ispunct as libc::c_int | _sch_isprint as libc::c_int) as libc::c_ushort,
    _sch_iscntrl as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
    0 as libc::c_int as libc::c_ushort,
];
#[no_mangle]
pub static mut _sch_tolower: [libc::c_uchar; 256] = [
    0 as libc::c_int as libc::c_uchar,
    1 as libc::c_int as libc::c_uchar,
    2 as libc::c_int as libc::c_uchar,
    3 as libc::c_int as libc::c_uchar,
    4 as libc::c_int as libc::c_uchar,
    5 as libc::c_int as libc::c_uchar,
    6 as libc::c_int as libc::c_uchar,
    7 as libc::c_int as libc::c_uchar,
    8 as libc::c_int as libc::c_uchar,
    9 as libc::c_int as libc::c_uchar,
    10 as libc::c_int as libc::c_uchar,
    11 as libc::c_int as libc::c_uchar,
    12 as libc::c_int as libc::c_uchar,
    13 as libc::c_int as libc::c_uchar,
    14 as libc::c_int as libc::c_uchar,
    15 as libc::c_int as libc::c_uchar,
    16 as libc::c_int as libc::c_uchar,
    17 as libc::c_int as libc::c_uchar,
    18 as libc::c_int as libc::c_uchar,
    19 as libc::c_int as libc::c_uchar,
    20 as libc::c_int as libc::c_uchar,
    21 as libc::c_int as libc::c_uchar,
    22 as libc::c_int as libc::c_uchar,
    23 as libc::c_int as libc::c_uchar,
    24 as libc::c_int as libc::c_uchar,
    25 as libc::c_int as libc::c_uchar,
    26 as libc::c_int as libc::c_uchar,
    27 as libc::c_int as libc::c_uchar,
    28 as libc::c_int as libc::c_uchar,
    29 as libc::c_int as libc::c_uchar,
    30 as libc::c_int as libc::c_uchar,
    31 as libc::c_int as libc::c_uchar,
    32 as libc::c_int as libc::c_uchar,
    33 as libc::c_int as libc::c_uchar,
    34 as libc::c_int as libc::c_uchar,
    35 as libc::c_int as libc::c_uchar,
    36 as libc::c_int as libc::c_uchar,
    37 as libc::c_int as libc::c_uchar,
    38 as libc::c_int as libc::c_uchar,
    39 as libc::c_int as libc::c_uchar,
    40 as libc::c_int as libc::c_uchar,
    41 as libc::c_int as libc::c_uchar,
    42 as libc::c_int as libc::c_uchar,
    43 as libc::c_int as libc::c_uchar,
    44 as libc::c_int as libc::c_uchar,
    45 as libc::c_int as libc::c_uchar,
    46 as libc::c_int as libc::c_uchar,
    47 as libc::c_int as libc::c_uchar,
    48 as libc::c_int as libc::c_uchar,
    49 as libc::c_int as libc::c_uchar,
    50 as libc::c_int as libc::c_uchar,
    51 as libc::c_int as libc::c_uchar,
    52 as libc::c_int as libc::c_uchar,
    53 as libc::c_int as libc::c_uchar,
    54 as libc::c_int as libc::c_uchar,
    55 as libc::c_int as libc::c_uchar,
    56 as libc::c_int as libc::c_uchar,
    57 as libc::c_int as libc::c_uchar,
    58 as libc::c_int as libc::c_uchar,
    59 as libc::c_int as libc::c_uchar,
    60 as libc::c_int as libc::c_uchar,
    61 as libc::c_int as libc::c_uchar,
    62 as libc::c_int as libc::c_uchar,
    63 as libc::c_int as libc::c_uchar,
    64 as libc::c_int as libc::c_uchar,
    'a' as i32 as libc::c_uchar,
    'b' as i32 as libc::c_uchar,
    'c' as i32 as libc::c_uchar,
    'd' as i32 as libc::c_uchar,
    'e' as i32 as libc::c_uchar,
    'f' as i32 as libc::c_uchar,
    'g' as i32 as libc::c_uchar,
    'h' as i32 as libc::c_uchar,
    'i' as i32 as libc::c_uchar,
    'j' as i32 as libc::c_uchar,
    'k' as i32 as libc::c_uchar,
    'l' as i32 as libc::c_uchar,
    'm' as i32 as libc::c_uchar,
    'n' as i32 as libc::c_uchar,
    'o' as i32 as libc::c_uchar,
    'p' as i32 as libc::c_uchar,
    'q' as i32 as libc::c_uchar,
    'r' as i32 as libc::c_uchar,
    's' as i32 as libc::c_uchar,
    't' as i32 as libc::c_uchar,
    'u' as i32 as libc::c_uchar,
    'v' as i32 as libc::c_uchar,
    'w' as i32 as libc::c_uchar,
    'x' as i32 as libc::c_uchar,
    'y' as i32 as libc::c_uchar,
    'z' as i32 as libc::c_uchar,
    91 as libc::c_int as libc::c_uchar,
    92 as libc::c_int as libc::c_uchar,
    93 as libc::c_int as libc::c_uchar,
    94 as libc::c_int as libc::c_uchar,
    95 as libc::c_int as libc::c_uchar,
    96 as libc::c_int as libc::c_uchar,
    'a' as i32 as libc::c_uchar,
    'b' as i32 as libc::c_uchar,
    'c' as i32 as libc::c_uchar,
    'd' as i32 as libc::c_uchar,
    'e' as i32 as libc::c_uchar,
    'f' as i32 as libc::c_uchar,
    'g' as i32 as libc::c_uchar,
    'h' as i32 as libc::c_uchar,
    'i' as i32 as libc::c_uchar,
    'j' as i32 as libc::c_uchar,
    'k' as i32 as libc::c_uchar,
    'l' as i32 as libc::c_uchar,
    'm' as i32 as libc::c_uchar,
    'n' as i32 as libc::c_uchar,
    'o' as i32 as libc::c_uchar,
    'p' as i32 as libc::c_uchar,
    'q' as i32 as libc::c_uchar,
    'r' as i32 as libc::c_uchar,
    's' as i32 as libc::c_uchar,
    't' as i32 as libc::c_uchar,
    'u' as i32 as libc::c_uchar,
    'v' as i32 as libc::c_uchar,
    'w' as i32 as libc::c_uchar,
    'x' as i32 as libc::c_uchar,
    'y' as i32 as libc::c_uchar,
    'z' as i32 as libc::c_uchar,
    123 as libc::c_int as libc::c_uchar,
    124 as libc::c_int as libc::c_uchar,
    125 as libc::c_int as libc::c_uchar,
    126 as libc::c_int as libc::c_uchar,
    127 as libc::c_int as libc::c_uchar,
    128 as libc::c_int as libc::c_uchar,
    129 as libc::c_int as libc::c_uchar,
    130 as libc::c_int as libc::c_uchar,
    131 as libc::c_int as libc::c_uchar,
    132 as libc::c_int as libc::c_uchar,
    133 as libc::c_int as libc::c_uchar,
    134 as libc::c_int as libc::c_uchar,
    135 as libc::c_int as libc::c_uchar,
    136 as libc::c_int as libc::c_uchar,
    137 as libc::c_int as libc::c_uchar,
    138 as libc::c_int as libc::c_uchar,
    139 as libc::c_int as libc::c_uchar,
    140 as libc::c_int as libc::c_uchar,
    141 as libc::c_int as libc::c_uchar,
    142 as libc::c_int as libc::c_uchar,
    143 as libc::c_int as libc::c_uchar,
    144 as libc::c_int as libc::c_uchar,
    145 as libc::c_int as libc::c_uchar,
    146 as libc::c_int as libc::c_uchar,
    147 as libc::c_int as libc::c_uchar,
    148 as libc::c_int as libc::c_uchar,
    149 as libc::c_int as libc::c_uchar,
    150 as libc::c_int as libc::c_uchar,
    151 as libc::c_int as libc::c_uchar,
    152 as libc::c_int as libc::c_uchar,
    153 as libc::c_int as libc::c_uchar,
    154 as libc::c_int as libc::c_uchar,
    155 as libc::c_int as libc::c_uchar,
    156 as libc::c_int as libc::c_uchar,
    157 as libc::c_int as libc::c_uchar,
    158 as libc::c_int as libc::c_uchar,
    159 as libc::c_int as libc::c_uchar,
    160 as libc::c_int as libc::c_uchar,
    161 as libc::c_int as libc::c_uchar,
    162 as libc::c_int as libc::c_uchar,
    163 as libc::c_int as libc::c_uchar,
    164 as libc::c_int as libc::c_uchar,
    165 as libc::c_int as libc::c_uchar,
    166 as libc::c_int as libc::c_uchar,
    167 as libc::c_int as libc::c_uchar,
    168 as libc::c_int as libc::c_uchar,
    169 as libc::c_int as libc::c_uchar,
    170 as libc::c_int as libc::c_uchar,
    171 as libc::c_int as libc::c_uchar,
    172 as libc::c_int as libc::c_uchar,
    173 as libc::c_int as libc::c_uchar,
    174 as libc::c_int as libc::c_uchar,
    175 as libc::c_int as libc::c_uchar,
    176 as libc::c_int as libc::c_uchar,
    177 as libc::c_int as libc::c_uchar,
    178 as libc::c_int as libc::c_uchar,
    179 as libc::c_int as libc::c_uchar,
    180 as libc::c_int as libc::c_uchar,
    181 as libc::c_int as libc::c_uchar,
    182 as libc::c_int as libc::c_uchar,
    183 as libc::c_int as libc::c_uchar,
    184 as libc::c_int as libc::c_uchar,
    185 as libc::c_int as libc::c_uchar,
    186 as libc::c_int as libc::c_uchar,
    187 as libc::c_int as libc::c_uchar,
    188 as libc::c_int as libc::c_uchar,
    189 as libc::c_int as libc::c_uchar,
    190 as libc::c_int as libc::c_uchar,
    191 as libc::c_int as libc::c_uchar,
    192 as libc::c_int as libc::c_uchar,
    193 as libc::c_int as libc::c_uchar,
    194 as libc::c_int as libc::c_uchar,
    195 as libc::c_int as libc::c_uchar,
    196 as libc::c_int as libc::c_uchar,
    197 as libc::c_int as libc::c_uchar,
    198 as libc::c_int as libc::c_uchar,
    199 as libc::c_int as libc::c_uchar,
    200 as libc::c_int as libc::c_uchar,
    201 as libc::c_int as libc::c_uchar,
    202 as libc::c_int as libc::c_uchar,
    203 as libc::c_int as libc::c_uchar,
    204 as libc::c_int as libc::c_uchar,
    205 as libc::c_int as libc::c_uchar,
    206 as libc::c_int as libc::c_uchar,
    207 as libc::c_int as libc::c_uchar,
    208 as libc::c_int as libc::c_uchar,
    209 as libc::c_int as libc::c_uchar,
    210 as libc::c_int as libc::c_uchar,
    211 as libc::c_int as libc::c_uchar,
    212 as libc::c_int as libc::c_uchar,
    213 as libc::c_int as libc::c_uchar,
    214 as libc::c_int as libc::c_uchar,
    215 as libc::c_int as libc::c_uchar,
    216 as libc::c_int as libc::c_uchar,
    217 as libc::c_int as libc::c_uchar,
    218 as libc::c_int as libc::c_uchar,
    219 as libc::c_int as libc::c_uchar,
    220 as libc::c_int as libc::c_uchar,
    221 as libc::c_int as libc::c_uchar,
    222 as libc::c_int as libc::c_uchar,
    223 as libc::c_int as libc::c_uchar,
    224 as libc::c_int as libc::c_uchar,
    225 as libc::c_int as libc::c_uchar,
    226 as libc::c_int as libc::c_uchar,
    227 as libc::c_int as libc::c_uchar,
    228 as libc::c_int as libc::c_uchar,
    229 as libc::c_int as libc::c_uchar,
    230 as libc::c_int as libc::c_uchar,
    231 as libc::c_int as libc::c_uchar,
    232 as libc::c_int as libc::c_uchar,
    233 as libc::c_int as libc::c_uchar,
    234 as libc::c_int as libc::c_uchar,
    235 as libc::c_int as libc::c_uchar,
    236 as libc::c_int as libc::c_uchar,
    237 as libc::c_int as libc::c_uchar,
    238 as libc::c_int as libc::c_uchar,
    239 as libc::c_int as libc::c_uchar,
    240 as libc::c_int as libc::c_uchar,
    241 as libc::c_int as libc::c_uchar,
    242 as libc::c_int as libc::c_uchar,
    243 as libc::c_int as libc::c_uchar,
    244 as libc::c_int as libc::c_uchar,
    245 as libc::c_int as libc::c_uchar,
    246 as libc::c_int as libc::c_uchar,
    247 as libc::c_int as libc::c_uchar,
    248 as libc::c_int as libc::c_uchar,
    249 as libc::c_int as libc::c_uchar,
    250 as libc::c_int as libc::c_uchar,
    251 as libc::c_int as libc::c_uchar,
    252 as libc::c_int as libc::c_uchar,
    253 as libc::c_int as libc::c_uchar,
    254 as libc::c_int as libc::c_uchar,
    255 as libc::c_int as libc::c_uchar,
];
#[no_mangle]
pub static mut _sch_toupper: [libc::c_uchar; 256] = [
    0 as libc::c_int as libc::c_uchar,
    1 as libc::c_int as libc::c_uchar,
    2 as libc::c_int as libc::c_uchar,
    3 as libc::c_int as libc::c_uchar,
    4 as libc::c_int as libc::c_uchar,
    5 as libc::c_int as libc::c_uchar,
    6 as libc::c_int as libc::c_uchar,
    7 as libc::c_int as libc::c_uchar,
    8 as libc::c_int as libc::c_uchar,
    9 as libc::c_int as libc::c_uchar,
    10 as libc::c_int as libc::c_uchar,
    11 as libc::c_int as libc::c_uchar,
    12 as libc::c_int as libc::c_uchar,
    13 as libc::c_int as libc::c_uchar,
    14 as libc::c_int as libc::c_uchar,
    15 as libc::c_int as libc::c_uchar,
    16 as libc::c_int as libc::c_uchar,
    17 as libc::c_int as libc::c_uchar,
    18 as libc::c_int as libc::c_uchar,
    19 as libc::c_int as libc::c_uchar,
    20 as libc::c_int as libc::c_uchar,
    21 as libc::c_int as libc::c_uchar,
    22 as libc::c_int as libc::c_uchar,
    23 as libc::c_int as libc::c_uchar,
    24 as libc::c_int as libc::c_uchar,
    25 as libc::c_int as libc::c_uchar,
    26 as libc::c_int as libc::c_uchar,
    27 as libc::c_int as libc::c_uchar,
    28 as libc::c_int as libc::c_uchar,
    29 as libc::c_int as libc::c_uchar,
    30 as libc::c_int as libc::c_uchar,
    31 as libc::c_int as libc::c_uchar,
    32 as libc::c_int as libc::c_uchar,
    33 as libc::c_int as libc::c_uchar,
    34 as libc::c_int as libc::c_uchar,
    35 as libc::c_int as libc::c_uchar,
    36 as libc::c_int as libc::c_uchar,
    37 as libc::c_int as libc::c_uchar,
    38 as libc::c_int as libc::c_uchar,
    39 as libc::c_int as libc::c_uchar,
    40 as libc::c_int as libc::c_uchar,
    41 as libc::c_int as libc::c_uchar,
    42 as libc::c_int as libc::c_uchar,
    43 as libc::c_int as libc::c_uchar,
    44 as libc::c_int as libc::c_uchar,
    45 as libc::c_int as libc::c_uchar,
    46 as libc::c_int as libc::c_uchar,
    47 as libc::c_int as libc::c_uchar,
    48 as libc::c_int as libc::c_uchar,
    49 as libc::c_int as libc::c_uchar,
    50 as libc::c_int as libc::c_uchar,
    51 as libc::c_int as libc::c_uchar,
    52 as libc::c_int as libc::c_uchar,
    53 as libc::c_int as libc::c_uchar,
    54 as libc::c_int as libc::c_uchar,
    55 as libc::c_int as libc::c_uchar,
    56 as libc::c_int as libc::c_uchar,
    57 as libc::c_int as libc::c_uchar,
    58 as libc::c_int as libc::c_uchar,
    59 as libc::c_int as libc::c_uchar,
    60 as libc::c_int as libc::c_uchar,
    61 as libc::c_int as libc::c_uchar,
    62 as libc::c_int as libc::c_uchar,
    63 as libc::c_int as libc::c_uchar,
    64 as libc::c_int as libc::c_uchar,
    'A' as i32 as libc::c_uchar,
    'B' as i32 as libc::c_uchar,
    'C' as i32 as libc::c_uchar,
    'D' as i32 as libc::c_uchar,
    'E' as i32 as libc::c_uchar,
    'F' as i32 as libc::c_uchar,
    'G' as i32 as libc::c_uchar,
    'H' as i32 as libc::c_uchar,
    'I' as i32 as libc::c_uchar,
    'J' as i32 as libc::c_uchar,
    'K' as i32 as libc::c_uchar,
    'L' as i32 as libc::c_uchar,
    'M' as i32 as libc::c_uchar,
    'N' as i32 as libc::c_uchar,
    'O' as i32 as libc::c_uchar,
    'P' as i32 as libc::c_uchar,
    'Q' as i32 as libc::c_uchar,
    'R' as i32 as libc::c_uchar,
    'S' as i32 as libc::c_uchar,
    'T' as i32 as libc::c_uchar,
    'U' as i32 as libc::c_uchar,
    'V' as i32 as libc::c_uchar,
    'W' as i32 as libc::c_uchar,
    'X' as i32 as libc::c_uchar,
    'Y' as i32 as libc::c_uchar,
    'Z' as i32 as libc::c_uchar,
    91 as libc::c_int as libc::c_uchar,
    92 as libc::c_int as libc::c_uchar,
    93 as libc::c_int as libc::c_uchar,
    94 as libc::c_int as libc::c_uchar,
    95 as libc::c_int as libc::c_uchar,
    96 as libc::c_int as libc::c_uchar,
    'A' as i32 as libc::c_uchar,
    'B' as i32 as libc::c_uchar,
    'C' as i32 as libc::c_uchar,
    'D' as i32 as libc::c_uchar,
    'E' as i32 as libc::c_uchar,
    'F' as i32 as libc::c_uchar,
    'G' as i32 as libc::c_uchar,
    'H' as i32 as libc::c_uchar,
    'I' as i32 as libc::c_uchar,
    'J' as i32 as libc::c_uchar,
    'K' as i32 as libc::c_uchar,
    'L' as i32 as libc::c_uchar,
    'M' as i32 as libc::c_uchar,
    'N' as i32 as libc::c_uchar,
    'O' as i32 as libc::c_uchar,
    'P' as i32 as libc::c_uchar,
    'Q' as i32 as libc::c_uchar,
    'R' as i32 as libc::c_uchar,
    'S' as i32 as libc::c_uchar,
    'T' as i32 as libc::c_uchar,
    'U' as i32 as libc::c_uchar,
    'V' as i32 as libc::c_uchar,
    'W' as i32 as libc::c_uchar,
    'X' as i32 as libc::c_uchar,
    'Y' as i32 as libc::c_uchar,
    'Z' as i32 as libc::c_uchar,
    123 as libc::c_int as libc::c_uchar,
    124 as libc::c_int as libc::c_uchar,
    125 as libc::c_int as libc::c_uchar,
    126 as libc::c_int as libc::c_uchar,
    127 as libc::c_int as libc::c_uchar,
    128 as libc::c_int as libc::c_uchar,
    129 as libc::c_int as libc::c_uchar,
    130 as libc::c_int as libc::c_uchar,
    131 as libc::c_int as libc::c_uchar,
    132 as libc::c_int as libc::c_uchar,
    133 as libc::c_int as libc::c_uchar,
    134 as libc::c_int as libc::c_uchar,
    135 as libc::c_int as libc::c_uchar,
    136 as libc::c_int as libc::c_uchar,
    137 as libc::c_int as libc::c_uchar,
    138 as libc::c_int as libc::c_uchar,
    139 as libc::c_int as libc::c_uchar,
    140 as libc::c_int as libc::c_uchar,
    141 as libc::c_int as libc::c_uchar,
    142 as libc::c_int as libc::c_uchar,
    143 as libc::c_int as libc::c_uchar,
    144 as libc::c_int as libc::c_uchar,
    145 as libc::c_int as libc::c_uchar,
    146 as libc::c_int as libc::c_uchar,
    147 as libc::c_int as libc::c_uchar,
    148 as libc::c_int as libc::c_uchar,
    149 as libc::c_int as libc::c_uchar,
    150 as libc::c_int as libc::c_uchar,
    151 as libc::c_int as libc::c_uchar,
    152 as libc::c_int as libc::c_uchar,
    153 as libc::c_int as libc::c_uchar,
    154 as libc::c_int as libc::c_uchar,
    155 as libc::c_int as libc::c_uchar,
    156 as libc::c_int as libc::c_uchar,
    157 as libc::c_int as libc::c_uchar,
    158 as libc::c_int as libc::c_uchar,
    159 as libc::c_int as libc::c_uchar,
    160 as libc::c_int as libc::c_uchar,
    161 as libc::c_int as libc::c_uchar,
    162 as libc::c_int as libc::c_uchar,
    163 as libc::c_int as libc::c_uchar,
    164 as libc::c_int as libc::c_uchar,
    165 as libc::c_int as libc::c_uchar,
    166 as libc::c_int as libc::c_uchar,
    167 as libc::c_int as libc::c_uchar,
    168 as libc::c_int as libc::c_uchar,
    169 as libc::c_int as libc::c_uchar,
    170 as libc::c_int as libc::c_uchar,
    171 as libc::c_int as libc::c_uchar,
    172 as libc::c_int as libc::c_uchar,
    173 as libc::c_int as libc::c_uchar,
    174 as libc::c_int as libc::c_uchar,
    175 as libc::c_int as libc::c_uchar,
    176 as libc::c_int as libc::c_uchar,
    177 as libc::c_int as libc::c_uchar,
    178 as libc::c_int as libc::c_uchar,
    179 as libc::c_int as libc::c_uchar,
    180 as libc::c_int as libc::c_uchar,
    181 as libc::c_int as libc::c_uchar,
    182 as libc::c_int as libc::c_uchar,
    183 as libc::c_int as libc::c_uchar,
    184 as libc::c_int as libc::c_uchar,
    185 as libc::c_int as libc::c_uchar,
    186 as libc::c_int as libc::c_uchar,
    187 as libc::c_int as libc::c_uchar,
    188 as libc::c_int as libc::c_uchar,
    189 as libc::c_int as libc::c_uchar,
    190 as libc::c_int as libc::c_uchar,
    191 as libc::c_int as libc::c_uchar,
    192 as libc::c_int as libc::c_uchar,
    193 as libc::c_int as libc::c_uchar,
    194 as libc::c_int as libc::c_uchar,
    195 as libc::c_int as libc::c_uchar,
    196 as libc::c_int as libc::c_uchar,
    197 as libc::c_int as libc::c_uchar,
    198 as libc::c_int as libc::c_uchar,
    199 as libc::c_int as libc::c_uchar,
    200 as libc::c_int as libc::c_uchar,
    201 as libc::c_int as libc::c_uchar,
    202 as libc::c_int as libc::c_uchar,
    203 as libc::c_int as libc::c_uchar,
    204 as libc::c_int as libc::c_uchar,
    205 as libc::c_int as libc::c_uchar,
    206 as libc::c_int as libc::c_uchar,
    207 as libc::c_int as libc::c_uchar,
    208 as libc::c_int as libc::c_uchar,
    209 as libc::c_int as libc::c_uchar,
    210 as libc::c_int as libc::c_uchar,
    211 as libc::c_int as libc::c_uchar,
    212 as libc::c_int as libc::c_uchar,
    213 as libc::c_int as libc::c_uchar,
    214 as libc::c_int as libc::c_uchar,
    215 as libc::c_int as libc::c_uchar,
    216 as libc::c_int as libc::c_uchar,
    217 as libc::c_int as libc::c_uchar,
    218 as libc::c_int as libc::c_uchar,
    219 as libc::c_int as libc::c_uchar,
    220 as libc::c_int as libc::c_uchar,
    221 as libc::c_int as libc::c_uchar,
    222 as libc::c_int as libc::c_uchar,
    223 as libc::c_int as libc::c_uchar,
    224 as libc::c_int as libc::c_uchar,
    225 as libc::c_int as libc::c_uchar,
    226 as libc::c_int as libc::c_uchar,
    227 as libc::c_int as libc::c_uchar,
    228 as libc::c_int as libc::c_uchar,
    229 as libc::c_int as libc::c_uchar,
    230 as libc::c_int as libc::c_uchar,
    231 as libc::c_int as libc::c_uchar,
    232 as libc::c_int as libc::c_uchar,
    233 as libc::c_int as libc::c_uchar,
    234 as libc::c_int as libc::c_uchar,
    235 as libc::c_int as libc::c_uchar,
    236 as libc::c_int as libc::c_uchar,
    237 as libc::c_int as libc::c_uchar,
    238 as libc::c_int as libc::c_uchar,
    239 as libc::c_int as libc::c_uchar,
    240 as libc::c_int as libc::c_uchar,
    241 as libc::c_int as libc::c_uchar,
    242 as libc::c_int as libc::c_uchar,
    243 as libc::c_int as libc::c_uchar,
    244 as libc::c_int as libc::c_uchar,
    245 as libc::c_int as libc::c_uchar,
    246 as libc::c_int as libc::c_uchar,
    247 as libc::c_int as libc::c_uchar,
    248 as libc::c_int as libc::c_uchar,
    249 as libc::c_int as libc::c_uchar,
    250 as libc::c_int as libc::c_uchar,
    251 as libc::c_int as libc::c_uchar,
    252 as libc::c_int as libc::c_uchar,
    253 as libc::c_int as libc::c_uchar,
    254 as libc::c_int as libc::c_uchar,
    255 as libc::c_int as libc::c_uchar,
];
